---
- name: Initialize the Kubernetes cluster using kubeadm
  command: kubeadm init --apiserver-advertise-address="{{ node_ip }}" --apiserver-cert-extra-sans="{{ node_ip }}"  --node-name k8s-master --service-cidr 10.96.0.0/12 --pod-network-cidr 10.244.0.0/16 --kubernetes-version v1.13.4
  ignore_errors: true

- name: Setup kubeconfig for vagrant user
  command: "{{ item }}"
  with_items:
    - mkdir -p /home/vagrant/.kube
    - cp -f /etc/kubernetes/admin.conf /home/vagrant/.kube/config
    - chown vagrant:vagrant /home/vagrant/.kube/config

- name: Install flannel pod network
  copy:
    src: kube-flannel.yml
    dest: kube-flannel.yml

- name: Install flannel pod network
  become: false
  command: kubectl apply -f kube-flannel.yml

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"