- name: Install common packages
  yum:
    name:
      - net-tools
      - vim
      - git
      - htop
      - tmux
      - tcpdump
      - lsof
      - telnet
      - wget
      - sysstat
    state: present